---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: pyroscope
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: pyroscope-agent
    app.kubernetes.io/name: pyroscope-agent
    app.kubernetes.io/version: "0.9.0"
  name: pyroscope-agent
  namespace: pyroscope
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: pyroscope-agent
      app.kubernetes.io/name: pyroscope-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pyroscope-agent
        app.kubernetes.io/name: pyroscope-agent
        app.kubernetes.io/version: "0.9.0"
    spec:
      containers:
        - name: pyroscope-agent
          args:
            - "connect"
            - "--spy-name"
            - "ebpfspy"
            - "--pid"
            - "-1"
            - "--server-address"
            - "http://pyroscope-server:4040"
            - "--log-level"
            - "debug"
          securityContext:
            privileged: true
            runAsGroup: 0
            runAsUser: 0
          image: pyroscope/pyroscope:0.9.0
          resources:
            {}
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
      hostPID: true
      volumes:
        - hostPath:
            path: /lib/modules
          name: modules
